In [1]:
import dhlab as dh
from dhlab import Corpus
from dhlab.text.parse import NER, POS, Models

In [2]:
# Bygg et korpus basert Agnar Mykle og hent ut urn-kolonnen som liste
urns = Corpus(doctype="digibok", author="mykle", title="røde").frame.urn
# Hent ut en urn
my_urn = urns.iloc[1]

In [3]:
l = Models()
l.models

['nb_core_news_lg',
 'da_core_news_lg',
 'nb_core_news_sm',
 'en_core_web_lg',
 'en_core_web_md',
 'da_core_news_trf']

In [4]:
result = NER(urn=my_urn, model="nb_core_news_sm", start_page=0, to_page=1000000)

/home/tita/koding/dhlab_stuff/digital_tekstanalyse/.venv/lib/python3.13/site-packages/dhlab/api/dhlab_api.py:80: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_json(resp.json())

In [5]:
result.ner

              token   ner  frekv
31              Ask   PER    813
127          Daniel   PER    115
1330           mann   PER     82
269             Gud   PER     82
1521              s   ORG     82
...             ...   ...    ...
907      bjeffes ut   LOC      1
906   bidige sjanse   PER      1
905         bibelen  MISC      1
904        bevæpnet   ORG      1
916        blåhvitt   ORG      1

[1962 rows x 3 columns]

In [6]:
res = POS(urn=urns.iloc[1], model=l.models[2], to_page=10000)

/home/tita/koding/dhlab_stuff/digital_tekstanalyse/.venv/lib/python3.13/site-packages/dhlab/api/dhlab_api.py:100: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_json(resp.json())

In [7]:
res.pos

,token,lemma,pos,dep,head,head_lemma,head_pos,head_head,head_head_lemma,head_head_pos,frekv
3653,",",",",PUNCT,punct,skamme,skamme,VERB,henne,henne,ADV,6
5019,",",",",PUNCT,punct,lagt,lægge,VERB,lagt,lægge,VERB,4
106994,nu,nu,ADV,advmod,lukker,lukke,VERB,sier,sie,VERB,4
5049,",",",",PUNCT,punct,kraftig,kraftig,ADJ,kraftig,kraftig,ADJ,4
15817,.,.,PUNCT,punct,Ja,ja,INTJ,Ja,ja,INTJ,4
...,...,...,...,...,...,...,...,...,...,...,...
52841,en,en,DET,det,pike,pike,NOUN,fant,fant,NOUN,1
52842,en,en,DET,det,angst,angst,NOUN,var,være,VERB,1
52843,en,en,DET,det,natt,natt,NOUN,holdt,holde,VERB,1
52844,en,en,DET,det,nesten,nesten,NOUN,tømt,tømme,VERB,1
52835,en,en,DET,det,kjøpte,kjøpte,PROPN,konsentrasjonsleirene,konsentrasjonsleir,NOUN,1