In [1]:
# Importer bibliotekene
import dhlab as dh # dhlab inneholder Corpus og andre nyttige funksjoner
from dhlab import nbtext as nb # Tekstverktøy

In [2]:
dh.Corpus(author='Vigdis Hjorth', limit=3)

,dhlabid,urn,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype,ocr_creator,ocr_timestamp
0,100479494,URN:NBN:no-nb_digibok_2017112048541,Ovllá ja Ánná,"Hjorth , Vigdis",oai:nb.bibsys.no:991505715424702202,5a03bbc053831fc3444f978c4c6bb994,,[Kárášjohka],20140101,2014,Davvi girji,sme / nob,Nordsamisk språk / Nordsamisk språk / lærebøke...,494.5586,novel,Skjønnlitteratur,digibok,nb,20060101
1,100595805,URN:NBN:no-nb_digibok_2022010707502,Snakk til meg : roman,"Hjorth , Vigdis",oai:nb.bibsys.no:999919888703902202,cd65bab187ae086e84290840e4eef443,,,2017,2017,Cappelen Damm,nob,Immigrasjon / Immigrasjon / Selvutvikling / Sj...,839.823,novel / text,Skjønnlitteratur,digibok,nb,20060101
2,100600967,URN:NBN:no-nb_digibok_2021101248019,Hysj,"Hjorth , Vigdis",oai:nb.bibsys.no:999919917860102202,6f2eb4929938bf20d37e0f7580066758,,,2018,2018,Cappelen Damm,nob,Prostitusjon / Prostitusjon,839.8238,novel / text,Skjønnlitteratur,digibok,nb,20060101

In [3]:
dh.Corpus(ddk='9*', subject='fiske', limit=3)

,dhlabid,urn,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype,ocr_creator,ocr_timestamp
0,100524021,URN:NBN:no-nb_digibok_2010120708082,Alvor og moro i Syltefjord,"Olsen , Margido",oai:nb.bibsys.no:999621092664702202,ad1f49e96b8fb7afd409642a360c3d3e,,,19960101,1996,"Lions Club, Båtsfjord",nob,Lokalhistorie / Kystkultur / Fiske / syltefjor...,948.4634,,Faglitteratur,digibok,nb,20060101
1,100023492,URN:NBN:no-nb_digibok_2010111108036,Flekkerøya i eldre og nyere tid : naturforhold...,"Rudolfsen , R. M.",oai:nb.bibsys.no:999200300174702202,beefefd19788857522497738855a6eea,8299253306,[Flekkerøy],19910101,1991,Flekkerøy historielag,nob,Slektshistorie / Lokalhistorie / oddernes / kr...,948.3211,,Faglitteratur,digibok,nb,20060101
2,100608588,URN:NBN:no-nb_digibok_2022021848029,Jevvaš : bosetting og bruk av Jevvaš-området f...,"Lindvall , Jan / Rundberg , Øyvind / Soleng , ...",oai:nb.bibsys.no:999920192895502202,a766dc6f57747ae1b307bd4541191282,,Olderdalen,2021,2021,Olderdalen jeger- og fiskerforening,nob,Jakt / Fangst / Historie / Kulturhistorie / Bo...,948.4552,tekst,Faglitteratur,digibok,nb,20060101

In [4]:
dh.Corpus(doctype='digibok', fulltext='demokrati', from_year=1990, to_year=2000, limit=3)

,dhlabid,urn,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype
41,100351558,URN:NBN:no-nb_digibok_2017082148117,Når situasjonen gjør det mulig - : om bosniske...,"Berg , Berit",oai:nb.bibsys.no:999908804864702202,5cdf014832d100ce89f7f4201a3ade20,8214011825,,19990101,1999,SINTEF IFIM,nob,Voluntary repatriation / Refugees / Return mig...,,,Uklassifisert,digibok
50,100434769,URN:NBN:no-nb_digibok_2008091604044,Handel med Europa,,oai:nb.bibsys.no:999809759644702202,657f7a90f448be26ed4af261af59b480,,Oslo,19980101,1998,Euro info,nob,europeisk / fellesskap / handel / eu / utenrik...,,,Uklassifisert,digibok
58,100486710,URN:NBN:no-nb_digibok_2009081804071,Partiavstand og partikoalisjoner,"Rommetvedt , Hilmar",oai:nb.bibsys.no:999214823614702202,5fbe0887a3666f1fe0c786306c524b29,,Stavanger,19910101,1991,Rogalandsforskning,nob,politiske / partier / norge / politisk / samar...,,,Uklassifisert,digibok

In [5]:
dh.Corpus(doctype='digibok', fulltext='her OR kan OR du OR legge OR inn OR flere OR søkeord', from_year=2010, to_year=2020, limit=3)

,dhlabid,urn,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype
33,100305615,URN:NBN:no-nb_digibok_2016072609111,Språkfakta Sogn og Fjordane 1646-2012,"Grepstad , Ottar",oai:nb.bibsys.no:991216053294702202,45e1efa7f292dfb9d608060bf883015a,,,20120101,2012,Nynorsk kultursentrum,nno,,306.44094838,,Faglitteratur,digibok
78,100664423,URN:NBN:no-nb_digibok_2020061748594,Grunnbok i Norges historie : fra vikingtid til...,"Helle, Knut",oai:nb.bibsys.no:991305610534702202,a5bc97c90f18107498c5abd6feb34aa9,,,2013,2013,Universitetsforl.,mul / nob / nno,Historie / noreg / norge / norsk / historie / ...,948.1 / 948.1 / 948.1 / 948.1 / 948.1 / 948.1,,Faglitteratur,digibok
30,100046904,URN:NBN:no-nb_digibok_2011033005007,"Forflytningskunnskap : aktivisering, hjelp og ...","Lunde , Per Halvor",oai:nb.bibsys.no:991000371864702202,1a4da75d040b3d1d051324155091afd6,,Oslo,20100101,2010,Gyldendal,nob,Moving and Lifting Patients / Lifting / Transp...,610.73028,,Faglitteratur,digibok

In [6]:
dh.Corpus(doctype='digavis', from_timestamp=20061201, to_timestamp=20070101, limit=3)

,dhlabid,urn,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype,ocr_creator,ocr_timestamp
0,200662790,URN:NBN:no-nb_digavis_glaamdalen_null_null_200...,glaamdalen,,,,,Kongsvinger,20061205,2006,,,,,,,digavis,nb,20060101
1,203777065,URN:NBN:no-nb_digavis_ostlandetsblad_null_null...,ostlandetsblad,,,,,,20061230,2006,,,,,,,digavis,nb,20060101
2,201929730,URN:NBN:no-nb_digavis_vestnytt_null_null_20061...,vestnytt,,,,,Øygarden,20061223,2006,,,,,,,digavis,nb,20060101

In [7]:
korpus = dh.Corpus(ddk="9*", subject="reindrift", from_year=1960, to_year=2020, limit=5)
korpus

,dhlabid,urn,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype,ocr_creator,ocr_timestamp
0,100388575,URN:NBN:no-nb_digibok_2018090407010,Landet bakom,"Johansen , Dag Ove",oai:nb.bibsys.no:991431678204702202,0262f5f99f6bdb2e664172e04aaa7bf2,,Rognan,20140101,2014,Bondes forl.,nob,Emigrasjon / Fra Norge / Emigrasjon / Fra Norg...,979.80049457 / 979.8 / 979.8004945,,Faglitteratur,digibok,nb,20060101
1,100472261,URN:NBN:no-nb_digibok_2010032307035,"I villreinens rike : Setesdal Vesthei , Ryfylk...","Frøstrup , Johan Christian / Bang-Andersen , S...",oai:nb.bibsys.no:990001151004702202,d6e1d58a454d2c15b44d9a225d948c1d,8291495149,,19990101,1999,Friluftsforl.,nob,Rein / Jakt / Landskap / Lokalhistorie / Reind...,948.3 / 799.2765,,Faglitteratur,digibok,nb,20060101
2,100039966,URN:NBN:no-nb_digibok_2011021108100,Guovdageainnu suohkangirji = : Kautokeino sogn...,"Keskitalo , Alf Isak",oai:nb.bibsys.no:999901445344702202,2d7197b6e525fc3c613354281c222971,8299471818,Guovdageaidnu,19980101,1998,Guovdageainnu suohkan,mul / nob / sme / eng,Lokalhistorie / Samer / Reindrift / Historie /...,948.4622,,Faglitteratur,digibok,nb,20060101
3,100293185,URN:NBN:no-nb_digibok_2009012000087,Bygdebok for Meråker . B. 1 : Gard og gruve,,oai:nb.bibsys.no:990300824474702202,3ac629ea23e018a266ddb2ba2a56299e,8299155940,[Meråker],20020101,2002,Meråker kommune,nob,Norge / Bygdebøker / Lokalhistorie / Samer / G...,948.42,,Faglitteratur,digibok,nb,20060101
4,100305533,URN:NBN:no-nb_digibok_2016072248015,Reindrifta i Jierddavuobme / Gjerdalen,"Pramli , Marthe Cecilie",oai:nb.bibsys.no:990100214774702202,fb0ad6ad5673bc0e60fa3f92320b929f,8279430024,[Drag],20000101,2000,Báhko,nob,Kulturlandskap / Reindrift / Historie / Kultur...,948.44,,Faglitteratur,digibok,nb,20060101

In [8]:
# Korpus-variabel + .corpus + .to_csv(filnavn)
korpus.frame.to_csv('korpus.csv', index=None)

In [9]:
# Korpus-variabel + .corpus + .csv(filnavn)
korpus.frame.to_excel('korpus.xlsx', index=None)

In [10]:
korpus = nb.restore_metadata_from_excel('korpus.xlsx')
korpus

,dhlabid,urn,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype,ocr_creator,ocr_timestamp
0,100388575,URN:NBN:no-nb_digibok_2018090407010,Landet bakom,"Johansen , Dag Ove",oai:nb.bibsys.no:991431678204702202,0262f5f99f6bdb2e664172e04aaa7bf2,NaN,Rognan,20140101,2014,Bondes forl.,nob,Emigrasjon / Fra Norge / Emigrasjon / Fra Norg...,979.80049457 / 979.8 / 979.8004945,NaN,Faglitteratur,digibok,nb,20060101
1,100472261,URN:NBN:no-nb_digibok_2010032307035,"I villreinens rike : Setesdal Vesthei , Ryfylk...","Frøstrup , Johan Christian / Bang-Andersen , S...",oai:nb.bibsys.no:990001151004702202,d6e1d58a454d2c15b44d9a225d948c1d,8.291495e+09,NaN,19990101,1999,Friluftsforl.,nob,Rein / Jakt / Landskap / Lokalhistorie / Reind...,948.3 / 799.2765,NaN,Faglitteratur,digibok,nb,20060101
2,100039966,URN:NBN:no-nb_digibok_2011021108100,Guovdageainnu suohkangirji = : Kautokeino sogn...,"Keskitalo , Alf Isak",oai:nb.bibsys.no:999901445344702202,2d7197b6e525fc3c613354281c222971,8.299472e+09,Guovdageaidnu,19980101,1998,Guovdageainnu suohkan,mul / nob / sme / eng,Lokalhistorie / Samer / Reindrift / Historie /...,948.4622,NaN,Faglitteratur,digibok,nb,20060101
3,100293185,URN:NBN:no-nb_digibok_2009012000087,Bygdebok for Meråker . B. 1 : Gard og gruve,NaN,oai:nb.bibsys.no:990300824474702202,3ac629ea23e018a266ddb2ba2a56299e,8.299156e+09,[Meråker],20020101,2002,Meråker kommune,nob,Norge / Bygdebøker / Lokalhistorie / Samer / G...,948.42,NaN,Faglitteratur,digibok,nb,20060101
4,100305533,URN:NBN:no-nb_digibok_2016072248015,Reindrifta i Jierddavuobme / Gjerdalen,"Pramli , Marthe Cecilie",oai:nb.bibsys.no:990100214774702202,fb0ad6ad5673bc0e60fa3f92320b929f,8.279430e+09,[Drag],20000101,2000,Báhko,nob,Kulturlandskap / Reindrift / Historie / Kultur...,948.44,NaN,Faglitteratur,digibok,nb,20060101

In [11]:
urns = nb.pure_urn("""

--- lim inn teksten her, så trekkes urn (bokas identifikator) ut i en liste:
Vigdis Hjorth : et forfatterportrett
Jenssen, Ruth | Biblioteksentralen
1994
(api)
id: 7f0b021f40bf6804bca32e5b79e8d66a
urn: URN:NBN:no-nb_digibok_2015090158054
isDigital: true
viewability: ALL
allowedFrom: NORWAY
contentClasses:
legaldeposit
bokhylla
jp2
Som om ingenting : bare om Vigdis Hjorth
Linneberg, Arild | Hjorth, Vigdis | Solstad, Dag
2009
(api)
id: 847bd73c3318f6874a66d0f969ba495a
urn: URN:NBN:no-nb_digibok_2011051820014
isDigital: true
viewability: ALL
allowedFrom: NB
contentClasses:
restricted
legaldeposit
jp2
Leve posthornet! : Vigdis Hjorth
Horn, Ellen | Riksteatret
2014
(api)
id: e6d86eeb4ac8509533d647c9793f01dc
urn: URN:NBN:no-nb_digibok_2014091948002
isDigital: true
viewability: ALL
allowedFrom: EVERYWHERE
contentClasses:
public
legaldeposit
jp2
Fryd og fare : essay om diktning og eksistens
Hjorth, Vigdis
2013
(api)
id: 5ecd6c199ff74aa7c57c2292b61df17d
urn: URN:NBN:no-nb_digibok_2018031548382
--- teksten er kuttet her
""")

In [12]:
# Legger til URN-prefix for hver URN
urns = ["URN:NBN:no-nb_digibok_" + x for x in urns]

In [13]:
c = dh.Corpus() # Tomt korpus objekt
c.extend_from_identifiers(identifiers=urns) # Legger til kodene vi hentet fra teksten over
c # Viser korpuset

,urn,dhlabid,title,authors,oaiid,sesamid,isbn10,city,timestamp,year,publisher,langs,subjects,ddc,genres,literaryform,doctype,ocr_creator,ocr_timestamp
0,URN:NBN:no-nb_digibok_2015090158054,100267417.0,Vigdis Hjorth : et forfatterportrett,"Jenssen , Ruth",oai:nb.bibsys.no:999409908064702202,7f0b021f40bf6804bca32e5b79e8d66a,,[Oslo],19940101.0,1994.0,Biblioteksentralen,nob,,,,Uklassifisert,digibok,nb,20060101.0
1,URN:NBN:no-nb_digibok_2018031548382,100367884.0,Fryd og fare : essay om diktning og eksistens,"Hjorth , Vigdis",oai:nb.bibsys.no:991334240574702202,5ecd6c199ff74aa7c57c2292b61df17d,,[Oslo],20130101.0,2013.0,Cappelen Damm,nob,Historisk framstilling / Norsk litteratur / Li...,809 / 839.824 / 809 / 839.824,,Faglitteratur,digibok,nb,20060101.0
2,URN:NBN:no-nb_digibok_2014091948002,100496097.0,Leve posthornet ! : Vigdis Hjorth,"Horn , Ellen",oai:nb.bibsys.no:991429153194702202,e6d86eeb4ac8509533d647c9793f01dc,,[Oslo],20140101.0,2014.0,Riksteatret,nob,,,,Uklassifisert,digibok,nb,20060101.0
3,URN:NBN:no-nb_digibok_2011051820014,100579548.0,Som om ingenting : bare om Vigdis Hjorth,"Linneberg , Arild / Hjorth , Vigdis / Solstad ...",oai:nb.bibsys.no:990925957234702202,847bd73c3318f6874a66d0f969ba495a,,[Oslo],20090101.0,2009.0,Cappelen Damm,nob,Norsk litteratur,839.828 / 839.828,festschrift,Faglitteratur,digibok,nb,20060101.0