In [1]:
from dhlab import Counts, totals, Corpus
from dhlab import graph_networkx_louvain as gnl
import pandas as pd
from dhlab import nbtext as nb

In [2]:
urn = "URN:NBN:no-nb_digibok_2021011848587"
bok = Counts([urn])

In [3]:
bok.frame.iloc[:, 0]

,              184
.              162
og              94
i               93
det             51
              ...
mofspillere      1
lell             1
nærmest          1
Solness          1
fremst           1
Name: 100431574, Length: 1597, dtype: Sparse[int64, 0]

In [4]:
tot = totals()

In [5]:
(bok.frame.iloc[:, 0] / tot.iloc[:, 0]).sort_values(ascending=False).head(20)

Hedda           0.00005
def             0.00003
Ivo            0.000026
Skjønberg      0.000023
Claes          0.000019
Gill           0.000017
oppførelse     0.000016
teatrene       0.000016
VAN            0.000015
væsen          0.000013
Alten          0.000013
Rosenkrantz    0.000011
Kaas           0.000011
poetiske        0.00001
ensemblet       0.00001
Høst            0.00001
Jæger           0.00001
kontra         0.000009
Peggy          0.000009
Vauxhall       0.000009
dtype: Sparse[float64, nan]

In [6]:
tot

                    freq
.             7655423257
,             5052171514
i             2531262027
og            2520268056
-             1314451583
...                  ...
tidspunkter       110667
dirigenter        110660
ondartet          110652
kulturtilbud      110652
trassig           110651

[50000 rows x 1 columns]

In [7]:
min_kamp_1 = Counts(["URN:NBN:no-nb_digibok_2014032405041"])
min_kamp_1.frame.head(20)

       100197175
,          14332
.           9480
og          5383
det         4430
jeg         4175
i           3657
var         3238
på          3152
-           2500
som         2463
en          2175
hadde       2010
ikke        1947
av          1900
den         1895
til         1815
med         1787
sa          1705
meg         1581
å           1575

In [8]:
(min_kamp_1.frame.iloc[:, 0] / tot.iloc[:,0]).sort_values(ascending=False).head(20).to_frame("ratio")

               ratio
Yngve       0.000572
Farmor      0.000376
pappas      0.000231
farmor      0.000203
Ylva         0.00019
skrudde     0.000154
Jada         0.00013
Fløgstad    0.000119
helte       0.000114
koppen      0.000108
kroppene    0.000108
gitaren     0.000105
jævla       0.000105
rekkverket  0.000104
cola        0.000103
røykte      0.000101
sigaretten  0.000101
kløv        0.000097
faen        0.000094
stuen        0.00009

In [9]:
# Frekvenslisiter for 20 Anne-Cath. Vestly bøker
vestly = Counts(
    Corpus(
        author="Anne*Vestly*",
        limit=20
    )
)
vestly.frame.head()

,100524772,100522279,100517398,100502723,100514864,100576702,100456958,100151409,100155956,100541708,100176063,100196353,100197114,100233761,100250991,100297528,100303061,100429382,100682537,100700495
",",2236,562,2187,2873,2007,2927,960,2596,2883,4956,2556,53,1299,366,1931,2027,68,1863,1838,2601
.,1637,737,2094,2304,2102,2676,1413,2167,2673,4672,2339,94,1255,329,2078,2113,87,1886,1997,2690
»,1055,132,984,1526,886,1400,478,1285,1399,2156,1231,18,541,151,765,885,7,1020,492,1283
«,1032,151,985,1526,890,1399,482,1288,1395,2170,1233,16,541,151,767,889,14,1024,493,1288
^,861,90,5,0,3,7,79,3,0,0,1,76,0,2,2,5,33,0,245,0

In [10]:
# Vi kan legge på et varmekart for lettere å få oversikt

nb.heatmap(vestly.frame.head(20))

In [11]:
def heatmap_loc(dr, ordliste, sorter=0):
    df = dr.loc[ordliste]
    return nb.heatmap(df.sort_values(by=df.columns[sorter], ascending=False))

In [12]:
# Her lager vi en funksjon heatmap_loc som vi bruker for å plukke ut enkelte ord fra korpuset som vi vil sammenlikne.


heatmap_loc(vestly.frame, "Mormor Morten Marte Ole Aleksander Guro Lillebror Knerten".split())

In [13]:
# Er forfatteren konsekvent når det kommer til ordformer?

heatmap_loc(vestly.frame, "sola solen".split())